### ISSUE TITLE
Error after document has been signed

### ISSUE THREAD

**Issue by scampoy** [keensoft/alfresco-esign-cert#40]
After document has been signed, before window was reloaded, Alfresco finalize sign process with and error. I have open alfresco.log file from my Alfresco instance and I have seen next error:

> Caused by: java.lang.IllegalArgumentException: Class {http://www.alfresco.com/model/signmodel/1.0}firstSignature has not been defined in the data dictionary
>         at org.alfresco.repo.policy.ClassPolicyDelegate.getList(ClassPolicyDelegate.java:127)
>         at org.alfresco.repo.policy.ClassPolicyDelegate.getList(ClassPolicyDelegate.java:112)
>         at org.alfresco.repo.version.common.AbstractVersionServiceImpl.invokeOnCreateVersion(AbstractVersionServiceImpl.java:271)
>         at org.alfresco.repo.version.common.AbstractVersionServiceImpl.invokeOnCreateVersion(AbstractVersionServiceImpl.java:191)
>         at org.alfresco.repo.version.Version2ServiceImpl.createVersion(Version2ServiceImpl.java:271)
>         at org.alfresco.repo.version.Version2ServiceImpl.createVersion(Version2ServiceImpl.java:118)
>         at org.alfresco.repo.version.VersionableAspect$2.doWork(VersionableAspect.java:536)
>         at org.alfresco.repo.version.VersionableAspect$2.doWork(VersionableAspect.java:531)
>         at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
>         at org.alfresco.repo.version.VersionableAspect.createVersionImpl(VersionableAspect.java:531)
>         at org.alfresco.repo.version.VersionableAspect.onContentUpdate(VersionableAspect.java:437)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:483)
>         at org.alfresco.repo.policy.JavaBehaviour$JavaMethodInvocationHandler.invoke(JavaBehaviour.java:174)
>         at com.sun.proxy.$Proxy75.onContentUpdate(Unknown Source)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:483)
>         at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:245)
>         ... 42 more

I have checked that firstSignature aspect is not definied on model...

**Comment by scampoy** [comment]
Solved on [version 1.6.0](https://github.com/keensoft/alfresco-esign-cert/tree/1.6.0)
