### ISSUE TITLE
Null pointer exception when uploading image using FTP

### ISSUE THREAD

**Issue by douglascrp** [keensoft/alfresco-esign-cert#9]
Hello.

I was trying to upload some image files to my dev alfresco server using FTP and got this error message.

```
2016-08-18 21:33:46,110  ERROR [org.alfresco.fileserver] [Sess_FTP6_xxx.xxx.xxx.xxx] Error from JLAN
 org.alfresco.error.AlfrescoRuntimeException: 07180079 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.node.NodeServicePolicies$OnCreateNodePolicy.onCreateNode(org.alfresco.service.cmr.repository.ChildAssociationRef) in transaction 69bb1342-bee3-4d5f-99eb-0569495f77dc
	at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:255)
	at org.alfresco.repo.policy.TransactionBehaviourQueue.beforeCommit(TransactionBehaviourQueue.java:134)
	at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.doBeforeCommit(TransactionSupportUtil.java:535)
	at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.doBeforeCommit(TransactionSupportUtil.java:514)
	at org.alfresco.util.transaction.TransactionSupportUtil$TransactionSynchronizationImpl.beforeCommit(TransactionSupportUtil.java:479)
	at org.springframework.transaction.support.TransactionSynchronizationUtils.triggerBeforeCommit(TransactionSynchronizationUtils.java:95)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerBeforeCommit(AbstractPlatformTransactionManager.java:925)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:738)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:724)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:475)
	at org.alfresco.util.transaction.SpringAwareUserTransaction.commit(SpringAwareUserTransaction.java:482)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:479)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:345)
	at org.alfresco.filesys.repo.CommandExecutorImpl.execute(CommandExecutorImpl.java:102)
	at org.alfresco.filesys.repo.NonTransactionalRuleContentDiskDriver.createFile(NonTransactionalRuleContentDiskDriver.java:256)
	at org.alfresco.filesys.repo.LegacyFileStateDriver.createFile(LegacyFileStateDriver.java:116)
	at org.alfresco.filesys.repo.BufferedContentDiskDriver.createFile(BufferedContentDiskDriver.java:468)
	at org.alfresco.jlan.ftp.FTPSrvSession.procStoreFile(FTPSrvSession.java:2318)
	at org.alfresco.jlan.ftp.FTPSrvSession.run(FTPSrvSession.java:5114)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at es.keensoft.alfresco.behaviour.CustomBehaviour.onCreateNode(CustomBehaviour.java:63)
	at sun.reflect.GeneratedMethodAccessor792.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.alfresco.repo.policy.JavaBehaviour$JavaMethodInvocationHandler.invoke(JavaBehaviour.java:174)
	at com.sun.proxy.$Proxy56.onCreateNode(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor538.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:243)
	... 19 more
```

This folder is the repository's root.

**Comment by angelborroy-ks** [comment]
I was an issue with 1.2.0 release. I've created a new one 1.2.1 solving this problem: https://github.com/keensoft/alfresco-esign-cert/releases/tag/1.2.1

**Comment by douglascrp** [comment]
May we close this one then?

**Comment by angelborroy-ks** [comment]
Did you tested (successfully) 1.2.1 with the same scenario?

**Comment by douglascrp** [comment]
Hey @angelborroy-ks 
Yes, it works perfectly now.
I'm closing the issue.
Thank you.
